import type { Metadata } from "next";
import { Playfair_Display } from "next/font/google";
import { Bebas_Neue } from "next/font/google";
import "./globals.css";

const Playfair_Displa = Playfair_Display({ subsets: ["latin"], weight: ["400", "500"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Playfair_Displa.className}>{children}</body>
    </html>
  );
}
